### ISSUE TITLE
Optimise the web socket data.

### ISSUE THREAD

**Issue by kirtanshetty** [ashok1994/LogFileMonitoring#2]
You are sending the entire file data each time. What if the file has 1000 lines of logs ? Will you send the entire content each time there is a change of one line in the file ?

**Comment by ashok1994** [comment]
Working on it , I am planning a better approach , will try to optimize as much as possible.

**Comment by ashok1994** [comment]
Now sending only appended lines to the front end , and reading forward from the last stats.size ,
closing for now , please let me know anything to change.
