### ISSUE TITLE
Functional issue

### ISSUE THREAD

**Issue by kirtanshetty** [ashok1994/LogFileMonitoring#3]
Issues in the code:

1. The code still does not all me to choose a file that I want to watch. I had not asked for a list of pre created files.
2. The code does not get the changes when I update the file rapidly, for example:
```
$ echo "fooooo" > logs/logc.txt && echo "aaaaaaaaaa" > logs/logc.txt && echo "bbbbbbbbbb" > logs/logc.txt && echo "cccccccc" > logs/logc.txt && echo "ddddddddd" > logs/logc.txt && echo "eeeeeeee" > logs/logc.txt && echo "ffffffff" > logs/logc.txt && echo "gggggggg" > logs/logc.txt && echo "hhhhhhhhhh" > logs/logc.txt
```

**Comment by ashok1994** [comment]
Planning to use streams , to achieve this, lets see how the performance goes

**Comment by ashok1994** [comment]
Added the new api and optimized the logging, please check and let me know if any changes required.
Closing for now
